# Generated by Django 2.1.15 on 2020-04-25 02:59

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=100)),
                ('qr', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('birthday', models.DateTimeField()),
                ('group', models.CharField(max_length=100)),
                ('sample_status', models.CharField(choices=[('normal', 'ORDINAIRE'), ('ugent', 'URGENT'), ('priority', 'PRIORITAIRE'), ('extern', 'EXTERNE')], default='normal', max_length=4)),
                ('doctor', models.CharField(max_length=100)),
                ('analysis', django.contrib.postgres.fields.jsonb.JSONField()),
                ('attachments', django.contrib.postgres.fields.jsonb.JSONField()),
                ('sampling_date', models.DateTimeField()),
                ('rdv', models.DateTimeField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
            },
        ),
    ]
