# Generated by Django 2.1.15 on 2020-04-26 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='analysis',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='attachments',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sample_status',
            field=models.CharField(choices=[('normal', 'ORDINAIRE'), ('ugent', 'URGENT'), ('priority', 'PRIORITAIRE'), ('extern', 'EXTERNE')], default='normal', max_length=50),
        ),
    ]
